import Link from 'next/link';
import { Building2,CircleDollarSign,FileText,Plus,Settings2,UserCog,UsersRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
const data={dashboard:{title:'Business Returns Dashboard',desc:'Monitor client returns, workflow status, and assignments.',action:'New Business',icon:Building2},clients:{title:'Clients',desc:'All client relationships in your tax office.',action:'Add Client',icon:UsersRound},businesses:{title:'Business Clients',desc:'Business entities and active tax engagements.',action:'New Business',icon:Building2},'tax-returns':{title:'Tax Returns',desc:'Track returns by tax year and workflow status.',action:'Add Return',icon:FileText},fees:{title:'Fees & Payments',desc:'Preparation fees, payments, and outstanding balances.',action:'Create Invoice',icon:CircleDollarSign},team:{title:'Team',desc:'Staff access, assignments, and administrative roles.',action:'Invite Staff',icon:UserCog},settings:{title:'Settings',desc:'Configure your tax office workspace and preferences.',action:'Save Changes',icon:Settings2}} as const;
export type RouteKind=keyof typeof data;const businesses=[['ABC Logistics LLC','1065','2025','In Preparation'],['XYZ Technology Inc','1120-S','2025','Waiting Documents'],['Luxury Nails Studio LLC','1065','2025','Review']];
export function RoutePage({kind}:{kind:RouteKind}){const page=data[kind],Icon=page.icon;return <main className="route-page"><header className="route-page-head"><div><span><Icon size={19}/></span><div><p>TAX CRM</p><h1>{page.title}</h1><small>{page.desc}</small></div></div><Button disabled aria-disabled="true"><Plus size={14}/>{page.action}</Button></header>{kind==='dashboard'?<DashboardBody/>:kind==='settings'?<SettingsBody/>:<ListBody kind={kind}/>}</main>}
function DashboardBody(){const records=[...businesses,['Minh Nguyen','1040','2025','Ready to File'],['Olivia Johnson','1040','2025','Completed']] as const;const metrics=[['Clients',new Set(records.map(row=>row[0])).size],['Business Returns',businesses.length],['Waiting Documents',records.filter(row=>row[3]==='Waiting Documents').length],['In Preparation',records.filter(row=>row[3]==='In Preparation').length],['Ready to File',records.filter(row=>row[3]==='Ready to File').length],['Completed',records.filter(row=>row[3]==='Completed').length]] as const;return <><section className="route-kpis">{metrics.map(row=><article key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></article>)}</section><ListBody kind="tax-returns"/></>}
function ListBody({kind}:{kind:RouteKind}){if(kind==='team')return <section className="route-card"><div className="route-rows">{[['Amy Tran','Owner'],['Daniel Lee','Preparer'],['Sarah Kim','Preparer']].map(row=><div key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><em>Active</em></div>)}</div></section>;if(kind==='fees')return <section className="route-card"><div className="route-rows">{businesses.map((row,i)=><div key={row[0]}><b>{row[0]}</b><span>Fee ${(2400+i*350).toLocaleString()}</span><em>{i===2?'Paid':'Outstanding'}</em></div>)}</div></section>;return <section className="route-card"><header><b>{kind==='clients'?'Business clients':kind==='businesses'?'Active businesses':'Business returns'}</b><span>{businesses.length} records</span></header><div className="route-table"><div><b>BUSINESS</b><b>ENTITY</b><b>YEAR</b><b>STATUS</b></div>{businesses.map((row,i)=><Link href={i===0?'/businesses/abc-logistics':'/businesses'} key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><span>{row[2]}</span><em>{row[3]}</em></Link>)}</div></section>}
function SettingsBody(){return <section className="route-card route-settings"><label>Office Name<input defaultValue="CRM EMY Tax Services"/></label><label>Default Tax Year<select defaultValue="2026"><option>2026</option><option>2025</option></select></label><label>Office Email<input defaultValue="office@crmemy.com"/></label><label>Time Zone<select><option>Pacific Time</option><option>Central Time</option><option>Eastern Time</option></select></label></section>}
