'use client';
import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';
export const Dialog=DialogPrimitive.Root;
export const DialogPortal=DialogPrimitive.Portal;
export const DialogClose=DialogPrimitive.Close;
export const DialogOverlay=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Overlay>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>>(({className,...props},ref)=><DialogPrimitive.Overlay ref={ref} className={cn('fixed inset-0 z-50 bg-[#0b1e33]/55 backdrop-blur-[2px]',className)} {...props}/>);DialogOverlay.displayName='DialogOverlay';
export const DialogContent=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>>(({className,children,...props},ref)=><DialogPortal><DialogOverlay/><DialogPrimitive.Content ref={ref} className={cn('fixed left-1/2 top-1/2 z-50 w-[calc(100%-24px)] max-w-5xl -translate-x-1/2 -translate-y-1/2 rounded-xl border border-[#dfe5eb] bg-white shadow-2xl outline-none',className)} {...props}>{children}<DialogPrimitive.Close className='absolute right-5 top-5 rounded-md p-1 text-[#7d8795] hover:bg-[#f1f3f6]' aria-label='Close'><X size={18}/></DialogPrimitive.Close></DialogPrimitive.Content></DialogPortal>);DialogContent.displayName='DialogContent';
export const DialogTitle=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Title>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>>(({className,...props},ref)=><DialogPrimitive.Title ref={ref} className={cn('text-lg font-bold text-[#172033]',className)} {...props}/>);DialogTitle.displayName='DialogTitle';
export const DialogDescription=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Description>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>>(({className,...props},ref)=><DialogPrimitive.Description ref={ref} className={cn('text-xs text-[#7a8492]',className)} {...props}/>);DialogDescription.displayName='DialogDescription';
